
name: check Game Documentation working
on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

permissions:
  pages: write
  deployments: write
  id-token: write
  
env:
  CONAN_REVISIONS_ENABLED: 1

jobs:
  docs:
    runs-on: windows-latest

    environment:
     name: github-pages
     url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check Installed Software
        run: where git & where python & where pip
        shell: cmd
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install Conan
        run: pip install conan
        
      - name: Install Doxygen
        run: conan download doxygen/1.9.4@#2af713e135f12722e3536808017ba086:e94378795f92fbf88bb8cef7f9c2f38c4ecf9126 --remote conancenter

      - name: Check current folder
        run: echo %cd%
